name: Hello World!

on: 
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs_on: ubuntu-18.04
    steps:
      - name: Say Hello
        run: 
          echo "Hello World!"             
